# Pull the official base image
FROM python:3.8-slim-buster

# Install PostgreSQL client
RUN apt-get update && apt-get install -y postgresql-client


# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /code

# Install dependencies
COPY requirements.txt /code/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy project
COPY . /code/