version: '3.8'

services:
  # db:
  #   image: postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./.env
  
  web:
    build: .
    environment:
      - IN_DOCKER_CONTAINER=1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - sqlite_data:/data
    ports:
      - 8000:8000
    # depends_on:
    #   - db
    env_file:
      - ./.env

volumes:
  # postgres_data:
  sqlite_data: