# Generated by Django 4.2.7 on 2023-12-10 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_variation_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.variation'),
            preserve_default=False,
        ),
    ]
