# Generated by Django 4.2.7 on 2023-12-11 10:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_alter_product_image_alter_productitem_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="product_image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
