# Generated by Django 4.2.7 on 2023-12-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0013_alter_product_image_alter_productitem_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="address_line1",
        ),
        migrations.RemoveField(
            model_name="address",
            name="address_line2",
        ),
        migrations.RemoveField(
            model_name="address",
            name="street_number",
        ),
        migrations.RemoveField(
            model_name="address",
            name="unit_number",
        ),
        migrations.AddField(
            model_name="address",
            name="billing_address",
            field=models.TextField(default="jos", verbose_name="Billing Address"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="email",
            field=models.EmailField(default="nabdulhaleem09@gmail.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="first_name",
            field=models.CharField(default="nas", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="last_name",
            field=models.CharField(default="nas", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="phone_number",
            field=models.CharField(
                default="09022563780", max_length=30, verbose_name="Phone Number"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="shipping_address",
            field=models.TextField(default="jos", verbose_name="Shipping Address "),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=30, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="sku",
            field=models.CharField(max_length=45),
        ),
    ]
