# Generated by Django 4.2.7 on 2024-01-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0016_rename_user_vendorstore_vendor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorprofile",
            name="address",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="firstname",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="lastname",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="phone",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="vendorstore",
            name="store_address",
            field=models.TextField(null=True),
        ),
    ]
