# Generated by Django 4.2.7 on 2024-01-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0017_alter_vendorprofile_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorprofile",
            name="business_name",
            field=models.CharField(default="nasiru-stores", max_length=255),
            preserve_default=False,
        ),
    ]
