# Generated by Django 4.2.7 on 2024-01-08 10:14

from django.conf import settings
import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.base


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0018_vendorprofile_business_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchOrdersView",
            fields=[
                (
                    "userprofile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shop.userprofile",
                    ),
                ),
            ],
            bases=(
                django.contrib.auth.mixins.LoginRequiredMixin,
                "shop.userprofile",
                django.views.generic.base.View,
            ),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
