# Generated by Django 4.2.7 on 2024-01-10 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0019_searchordersview_alter_vendorprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendororder",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="vendororder",
            name="order",
        ),
        migrations.AddField(
            model_name="vendororder",
            name="order_item",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.orderitem",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendororder",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("S", "Shipped"), ("D", "Delivered")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="vendororder",
            name="vendor",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.vendorprofile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vendororder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
