# Generated by Django 4.2.7 on 2024-01-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0020_remove_vendororder_customer_remove_vendororder_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorstore",
            name="store_category",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vendorstore",
            name="store_city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vendorstore",
            name="store_country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vendorstore",
            name="store_description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="vendorstore",
            name="store_state",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vendorstore",
            name="store_sub_category",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
