# Generated by Django 4.2.7 on 2024-01-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0021_vendorstore_store_category_vendorstore_store_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendororder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Pending", "Shipped"),
                    ("Delivered", "Delivered"),
                ],
                default="Pending",
                max_length=11,
            ),
        ),
    ]
